<template>
  <div>
    <el-table
      :data="tableData"
      style="width: 100%"
      row-key="id"
      border
      default-expand-all
    >
      <el-table-column prop="name" label="名称" width="180" />
      <el-table-column prop="type" label="类型" width="120" />
      <el-table-column prop="maxLength" label="最大长度" width="100" />
      <el-table-column prop="required" label="是否必须" width="100" />
      <el-table-column prop="example" label="示例值" width="120" />
      <el-table-column prop="description" label="描述" />
    </el-table>
  </div>
</template>
<script lang="ts" setup>
const tableData = [
  {
    id: 1,
    name: "partnerType",
    type: "string",
    maxLength: "",
    required: "是",
    example: "2",
    description: "合作模式，1：集团客户；2：非集团客户",
  },
  {
    id: 2,
    name: "orderType",
    type: "string",
    maxLength: "",
    required: "是",
    example: "1",
    description:
      "partnerType为1时，orderType：1：全网件 2：预约件。 partnerType为2时，orderType：1：全网件 2：预约件（返回运单号） 3：预约件（不返回运单号） 4：星联全网件",
  },
  {
    id: 3,
    name: "partnerOrderCode",
    type: "string",
    maxLength: "",
    required: "是",
    example: "",
    description: "商家自主定义合作商订单号",
  },
  {
    id: 4,
    name: "accountInfo",
    type: "Object",
    maxLength: "",
    required: "否",
    example: "",
    description: "账号信息",
    children: [
      {
        id: 401,
        name: "accountId",
        type: "string",
        maxLength: "",
        required: "否",
        example: "test",
        description: "电子面单账号（partnerType为2，orderType传1,2,4时必传）",
      },
      {
        id: 402,
        name: "accountPassword",
        type: "string",
        maxLength: "",
        required: "否",
        example: "",
        description: "电子面单密码（测试环境传ZTO123）",
      },
      {
        id: 403,
        name: "type",
        type: "short",
        maxLength: "",
        required: "否",
        example: "1",
        description: "单号类型:1.普通电子面单；74.星联电子面单；默认是1",
      },
      {
        id: 404,
        name: "customerId",
        type: "string",
        maxLength: "",
        required: "否",
        example: "GPG1576724269",
        description: "集团客户编码（partnerType传1时必传）",
      },
      {
        id: 405,
        name: "billCode",
        type: "string",
        maxLength: "",
        required: "否",
        example: "",
        description: "运单号",
      },
    ],
  },
  {
    id: 5,
    name: "senderInfo",
    type: "Object",
    maxLength: "",
    required: "是",
    example: "",
    description: "发件人信息",
    children: [
      {
        id: 501,
        name: "senderId",
        type: "string",
        maxLength: "",
        required: "否",
        example: "senderInfo",
        description: "",
      },
      {
        id: 502,
        name: "senderName",
        type: "string",
        maxLength: "",
        required: "是",
        example: "张三",
        description: "发件人姓名",
      },
      {
        id: 503,
        name: "senderPhone",
        type: "string",
        maxLength: "",
        required: "否",
        example: "010-22226789",
        description: "发件人座机（与senderMobile二者不能同时为空）",
      },
      {
        id: 504,
        name: "senderMobile",
        type: "string",
        maxLength: "",
        required: "否",
        example: "13900000000",
        description: "发件人手机号（与senderPhone二者不能同时为空）",
      },
      {
        id: 505,
        name: "senderProvince",
        type: "string",
        maxLength: "",
        required: "是",
        example: "上海",
        description: "发件人省",
      },
      {
        id: 506,
        name: "senderCity",
        type: "string",
        maxLength: "",
        required: "是",
        example: "上海市",
        description: "发件人市",
      },
      {
        id: 507,
        name: "senderDistrict",
        type: "string",
        maxLength: "",
        required: "是",
        example: "青浦区",
        description: "发件人区",
      },
      {
        id: 508,
        name: "senderAddress",
        type: "string",
        maxLength: "",
        required: "是",
        example: "华志路",
        description: "发件人详细地址",
      },
    ],
  },
  {
    id: 6,
    name: "receiveInfo",
    type: "Object",
    maxLength: "",
    required: "是",
    example: "",
    description: "收件人信息",
    children: [
      {
        id: 601,
        name: "receiverName",
        type: "string",
        maxLength: "",
        required: "是",
        example: "Jone Star",
        description: "收件人姓名",
      },
      {
        id: 602,
        name: "receiverPhone",
        type: "string",
        maxLength: "",
        required: "否",
        example: "021-87654321",
        description: "收件人座机（与receiverMobile二者不能同时为空）",
      },
      {
        id: 603,
        name: "receiverMobile",
        type: "string",
        maxLength: "",
        required: "否",
        example: "13500000000",
        description: "收件人手机号（与 receiverPhone二者不能同时为空）",
      },
      {
        id: 604,
        name: "receiverProvince",
        type: "string",
        maxLength: "",
        required: "是",
        example: "上海",
        description: "收件人省",
      },
      {
        id: 605,
        name: "receiverCity",
        type: "string",
        maxLength: "",
        required: "是",
        example: "上海市",
        description: "收件人市",
      },
      {
        id: 606,
        name: "receiverDistrict",
        type: "string",
        maxLength: "",
        required: "是",
        example: "闵行区",
        description: "收件人区",
      },
      {
        id: 607,
        name: "receiverAddress",
        type: "string",
        maxLength: "",
        required: "是",
        example: "申贵路1500号",
        description: "收件人详细地址",
      },
    ],
  },
  {
    id: 7,
    name: "orderVasList",
    type: "Object[]",
    maxLength: "",
    required: "否",
    example: "",
    description: "增值服务信息",
    children: [
      {
        id: 701,
        name: "vasType",
        type: "string",
        maxLength: "",
        required: "否",
        example: "COD",
        description:
          "增值类型 （COD：代收； vip：中通标快； insured：保价； receiveReturnService：签单返回； twoHour：两小时；standardExpress：中通好快）",
      },
      {
        id: 702,
        name: "vasAmount",
        type: "long",
        maxLength: "",
        required: "否",
        example: "100000",
        description:
          "增值价格，如果增值类型涉及金额会校验，vasType为COD、insured时不能为空，单位：分",
      },
      {
        id: 703,
        name: "vasPrice",
        type: "long",
        maxLength: "",
        required: "否",
        example: "",
        description: "增值价格（暂时不用）",
      },
      {
        id: 704,
        name: "vasDetail",
        type: "string",
        maxLength: "",
        required: "否",
        example: "",
        description: "增值详情",
      },
      {
        id: 705,
        name: "accountNo",
        type: "string",
        maxLength: "",
        required: "否",
        example: "",
        description: "代收账号（有代收货款增值时必填）",
      },
    ],
  },
  {
    id: 706,
    name: "hallCode",
    type: "string",
    maxLength: "",
    required: "否",
    example: "S2044",
    description: "门店/仓库编码（partnerType为1时可使用）",
  },
  {
    id: 707,
    name: "siteCode",
    type: "string",
    maxLength: "",
    required: "否",
    example: "02100",
    description: "网点code（orderVasList.vasType为receiveReturnService必填）",
  },
  {
    id: 708,
    name: "siteName",
    type: "string",
    maxLength: "",
    required: "否",
    example: "上海",
    description: "网点名称（orderVasList.vasType为receiveReturnService必填）",
  },
  {
    id: 8,
    name: "summaryInfo",
    type: "Object",
    maxLength: "",
    required: "否",
    example: "",
    description: "汇总信息",
    children: [
      {
        id: 801,
        name: "size",
        type: "string",
        maxLength: "",
        required: "否",
        example: "",
        description:
          "订单包裹大小（单位：厘米、格式：”长，宽，高”，用半角的逗号来分隔）",
      },
      {
        id: 802,
        name: "quantity",
        type: "integer",
        maxLength: "",
        required: "否",
        example: "3",
        description: "订单包裹内货物总数量",
      },
      {
        id: 803,
        name: "price",
        type: "BigDecimal",
        maxLength: "",
        required: "否",
        example: "30",
        description: "商品总价值（单位：元）",
      },
      {
        id: 804,
        name: "freight",
        type: "BigDecimal",
        maxLength: "",
        required: "否",
        example: "20",
        description: "运输费（单位：元）",
      },
      {
        id: 805,
        name: "premium",
        type: "BigDecimal",
        maxLength: "",
        required: "否",
        example: "10",
        description: "险费（单位：元）",
      },
      {
        id: 806,
        name: "startTime",
        type: "date",
        maxLength: "",
        required: "否",
        example: "2020-12-10 12:00:00",
        description: "取件开始时间",
      },
      {
        id: 807,
        name: "endTime",
        type: "date",
        maxLength: "",
        required: "否",
        example: "2020-12-10 12:00:00",
        description: "取件截止时间",
      },
    ],
  },
  {
    id: 808,
    name: "remark",
    type: "string",
    maxLength: "",
    required: "否",
    example: "小吉下单",
    description: "备注",
  },
  {
    id: 9,
    name: "orderItems",
    type: "Object[]",
    maxLength: "",
    required: "否",
    example: "",
    description: "物品信息",
    children: [
      {
        id: 901,
        name: "name",
        type: "string",
        maxLength: "",
        required: "否",
        example: "",
        description: "货品名称",
      },
      {
        id: 902,
        name: "category",
        type: "string",
        maxLength: "",
        required: "否",
        example: "",
        description: "商品分类",
      },
      {
        id: 903,
        name: "material",
        type: "string",
        maxLength: "",
        required: "否",
        example: "",
        description: "商品材质",
      },
      {
        id: 904,
        name: "size",
        type: "string",
        maxLength: "",
        required: "否",
        example: "",
        description: "大小（长,宽,高）(单位：厘米), 用半角的逗号来分隔长宽高",
      },
      {
        id: 905,
        name: "weight",
        type: "long",
        maxLength: "",
        required: "否",
        example: "",
        description: "重量（单位：克)",
      },
      {
        id: 906,
        name: "unitprice",
        type: "integer",
        maxLength: "",
        required: "否",
        example: "",
        description: "单价(单位:元)",
      },
      {
        id: 907,
        name: "quantity",
        type: "integer",
        maxLength: "",
        required: "否",
        example: "",
        description: "货品数量",
      },
      {
        id: 908,
        name: "remark",
        type: "string",
        maxLength: "",
        required: "否",
        example: "",
        description: "货品备注",
      },
    ],
  },
  {
    id: 10,
    name: "cabinet",
    type: "Object",
    maxLength: "",
    required: "否",
    example: "",
    description: "机柜信息",
    children: [
      {
        id: 1001,
        name: "address",
        type: "string",
        maxLength: "",
        required: "否",
        example: "",
        description: "地址",
      },
      {
        id: 1002,
        name: "specification",
        type: "integer",
        maxLength: "",
        required: "否",
        example: "",
        description: "格口规格 格口大小( 1 大 2 中 3 小）",
      },
      {
        id: 1003,
        name: "code",
        type: "string",
        maxLength: "",
        required: "否",
        example: "",
        description: "开箱码",
      },
    ],
  },
];
</script>
